apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
spec:
  replicas: 3
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
        - name: details
          image: gcr.io/practica-443518/details-10  # Imagen subida a Docker Hub
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: details
spec:
  selector:
    app: details
  ports:
    - protocol: TCP
      port: 9080
  type: ClusterIP
