apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
        - name: ratings
          image: gcr.io/practica-443518/ratings-10  # Imagen subida a Docker Hub
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
    - protocol: TCP
      port: 9080
  type: ClusterIP
