apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
        - name: reviews-v2
          image: gcr.io/practica-443518/reviews-10:v2  # Imagen subida a Docker Hub
          env:
          - name: SERVICE_VERSION
            value: "v2"
          - name: ENABLE_RATINGS
            value: "true"
          - name: STAR_COLOR
            value: "black"
          ports:
            - containerPort: 9080
