apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      containers:
        - name: reviews-v3
          image: gcr.io/practica-443518/reviews-10:v3  # Imagen subida a Docker Hub
          ports:
            - containerPort: 9080
