FROM python:3.7-slim

WORKDIR /opt/microservices

# Actualizar pip a la última versión
RUN pip install --upgrade pip

# Copiar el archivo requirements.txt
COPY requirements.txt .

# Instalar dependencias usando el resolver antiguo
RUN pip install --use-deprecated=legacy-resolver -r requirements.txt

# Copiar el código de la aplicación y otros recursos necesarios
COPY productpage.py .
COPY templates/ ./templates/
COPY static/ ./static/

# Exponer el puerto
EXPOSE 9080

# Definir el comando de inicio
CMD ["python3", "productpage.py", "9080"]

